/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kovacevic.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import kovacevic.model.AnalizaCijene;
import kovacevic.model.GrupacijaNorme;

/**
 *
 * @author Marko Kovačević
 */
public class FormaTroskovnici extends JFrame {

    /**
     * Creates new form FormaAnalizaCijene
     */
    public FormaTroskovnici() {
        initComponents();
        setTitle("Troškovnici");
        popunjavanjeTabliceAnalizaCijene(tblTroskovnici);

    }

    private void popunjavanjeTabliceAnalizaCijene(JTable tablica) {
        String[] coulumnName = {"Rb. (Id)", "Oznaka", "Naslov",
            "Građevina", "Naručitelj", "Datum izrade"};
        DefaultTableModel model = (DefaultTableModel) tablica.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(coulumnName);
        int rb = 0;
//        if (rezultatiAnalizaCijena != null) {
//            for (AnalizaCijene analizaCijene : rezultatiAnalizaCijena) {
//                rb++;
//                model.addRow(new Object[]{
//                    rb + ". (" + analizaCijene.getId() + ")",
//                    analizaCijene.getOznakaNorme(),
//                    analizaCijene.getOpis(),
//                    analizaCijene.getJedinicaMjere(),
//                    analizaCijene.getUkupanNormativVremena(),
//                    analizaCijene.getSveukupanIznos()
//                });
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPregledTroskovnika = new javax.swing.JPanel();
        lblTroskovnici = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTroskovnici = new javax.swing.JTable();
        txtTraziTroskovnikNaslov = new javax.swing.JTextField();
        btnDodajTroskovnik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 0));

        lblTroskovnici.setText("Troškovnici:");

        tblTroskovnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTroskovnici);

        txtTraziTroskovnikNaslov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraziTroskovnikNaslovActionPerformed(evt);
            }
        });

        btnDodajTroskovnik.setText("Dodaj");
        btnDodajTroskovnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTroskovnikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPregledTroskovnikaLayout = new javax.swing.GroupLayout(jpPregledTroskovnika);
        jpPregledTroskovnika.setLayout(jpPregledTroskovnikaLayout);
        jpPregledTroskovnikaLayout.setHorizontalGroup(
            jpPregledTroskovnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPregledTroskovnikaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPregledTroskovnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(jpPregledTroskovnikaLayout.createSequentialGroup()
                        .addComponent(lblTroskovnici)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpPregledTroskovnikaLayout.createSequentialGroup()
                        .addComponent(txtTraziTroskovnikNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajTroskovnik)))
                .addContainerGap())
        );
        jpPregledTroskovnikaLayout.setVerticalGroup(
            jpPregledTroskovnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPregledTroskovnikaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTroskovnici)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPregledTroskovnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTraziTroskovnikNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajTroskovnik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPregledTroskovnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPregledTroskovnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTraziTroskovnikNaslovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraziTroskovnikNaslovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraziTroskovnikNaslovActionPerformed

    private void btnDodajTroskovnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTroskovnikActionPerformed
        new FormaTroskovnik(true, false).setVisible(true);
    }//GEN-LAST:event_btnDodajTroskovnikActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajTroskovnik;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpPregledTroskovnika;
    private javax.swing.JLabel lblTroskovnici;
    private javax.swing.JTable tblTroskovnici;
    private javax.swing.JTextField txtTraziTroskovnikNaslov;
    // End of variables declaration//GEN-END:variables

}
