/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kovacevic.view;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import kovacevic.controller.HibernateObrada;
import kovacevic.model.AnalizaCijene;
import kovacevic.model.AnalizaMaterijal;
import kovacevic.model.Materijal;
import kovacevic.pomocno.HibernateUtil;

/**
 *
 * @author Marko Kovačević
 */
public class FormaAnalizaMaterijal extends Forma<AnalizaMaterijal> {

    private List<AnalizaMaterijal> analizaMaterijala;
    private List<Materijal> materijal;

    /**
     * Creates new form FormaRad
     */
    public FormaAnalizaMaterijal() {
        initComponents();
        setTitle("Analiza Materijala");
        obrada = new HibernateObrada();

        ucitaj();
        ucitajAnalizaCijene();
        ucitajMaterijal();
    }

//private void ucitajMaterijal(){
//        DefaultComboBoxModel<AnalizaCijene> cbm = new DefaultComboBoxModel<>();
//        materijal.stream()
//}

    
    
    
//
//private void ucitajOpisIzOdabraneNorme(){
//    cmbOznakaNorme.addItemListener(new ItemListener() {
//        @Override
//        public void itemStateChanged(ItemEvent ie) {
//           if (ie.getStateChange() == ItemEvent.SELECTED){
//               AnalizaCijene opis = (AnalizaCijene) cmbOznakaNorme.getSelectedItem();
//               tarOpisStavkeTroskovnika.setText(opis.toString());
//
//               
//           }
//        }
//    });
//}
// 
    @Override
    protected void ucitaj() {
        DefaultListModel<AnalizaMaterijal> m = new DefaultListModel<>();
        lstAnalizaMaterijala.setModel(m);
        analizaMaterijala = HibernateUtil.getSession().createQuery("from AnalizaMaterijal a where a.obrisan=false").list();
        analizaMaterijala.forEach((s) -> {
            m.addElement(s);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAnalizaMaterijala = new javax.swing.JList<>();
        lblKolicina = new javax.swing.JLabel();
        lblJedinicaMjere = new javax.swing.JLabel();
        lblJedinicnaCijena = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        txtJedinicaMjere = new javax.swing.JTextField();
        txtJedinicnaCijenaMaterijal = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblMaterijal = new javax.swing.JLabel();
        lblOznakaNorme = new javax.swing.JLabel();
        cmbOznakaNorme = new javax.swing.JComboBox<>();
        cmbMatrijal = new javax.swing.JComboBox<>();
        lblCijenaMaterijala = new javax.swing.JLabel();
        txtCijenaMaterijal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarOpisNorme = new javax.swing.JTextArea();
        lblBrupaRadova1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(895, 400));
        setPreferredSize(new java.awt.Dimension(874, 400));
        setSize(new java.awt.Dimension(0, 0));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(450, 23));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 130));

        lstAnalizaMaterijala.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAnalizaMaterijala.setToolTipText("");
        lstAnalizaMaterijala.setDropMode(javax.swing.DropMode.INSERT);
        lstAnalizaMaterijala.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lstAnalizaMaterijala.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAnalizaMaterijalaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAnalizaMaterijala);

        lblKolicina.setText("Količina:");

        lblJedinicaMjere.setText("Jedinica mjere:");

        lblJedinicnaCijena.setText("Jedinična cijena:");
        lblJedinicnaCijena.setToolTipText("");

        txtKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolicinaActionPerformed(evt);
            }
        });

        txtJedinicnaCijenaMaterijal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJedinicnaCijenaMaterijalActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblMaterijal.setText("Materijal:");
        lblMaterijal.setToolTipText("");

        lblOznakaNorme.setText("Oznaka norme:");

        cmbOznakaNorme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOznakaNormeActionPerformed(evt);
            }
        });

        cmbMatrijal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatrijalActionPerformed(evt);
            }
        });

        lblCijenaMaterijala.setText("Cijena materijala:");
        lblCijenaMaterijala.setToolTipText("");

        txtCijenaMaterijal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCijenaMaterijalActionPerformed(evt);
            }
        });

        jScrollPane2.setToolTipText("");

        tarOpisNorme.setColumns(20);
        tarOpisNorme.setRows(5);
        tarOpisNorme.setWrapStyleWord(true);
        tarOpisNorme.setPreferredSize(new java.awt.Dimension(104, 79));
        jScrollPane2.setViewportView(tarOpisNorme);
        tarOpisNorme.setLineWrap(true);

        lblBrupaRadova1.setText("Opis norme:");
        lblBrupaRadova1.setToolTipText("");

        jLabel1.setText("količina*jedinična cijena");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOznakaNorme)
                    .addComponent(lblBrupaRadova1)
                    .addComponent(lblMaterijal)
                    .addComponent(lblKolicina)
                    .addComponent(lblJedinicaMjere)
                    .addComponent(lblJedinicnaCijena)
                    .addComponent(lblCijenaMaterijala))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbOznakaNorme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(cmbMatrijal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJedinicaMjere)
                    .addComponent(txtKolicina)
                    .addComponent(txtJedinicnaCijenaMaterijal)
                    .addComponent(txtCijenaMaterijal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbOznakaNorme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOznakaNorme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrupaRadova1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaterijal)
                            .addComponent(cmbMatrijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJedinicaMjere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJedinicaMjere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKolicina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJedinicnaCijenaMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJedinicnaCijena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCijenaMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCijenaMaterijala)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni)
                            .addComponent(btnObrisi)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        entitet = new AnalizaMaterijal();
        spremi();
        repaint();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if (lstAnalizaMaterijala.getSelectedValue() == null) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        spremi();

    }//GEN-LAST:event_btnPromjeniActionPerformed
    @Override
    protected void spremi() {
        entitet.setJedinicaMjere(txtJedinicaMjere.getText());
        entitet.setKolicina(new BigDecimal(txtKolicina.getText()));
        entitet.setJedinicnaCijenaMaterijal(new BigDecimal(txtJedinicnaCijenaMaterijal.getText()));
        entitet.setCijenaMaterijal(new BigDecimal(txtCijenaMaterijal.getText()));
        entitet.setAnalizaCijene((AnalizaCijene) cmbOznakaNorme.getSelectedItem());
        entitet.setMaterijal((Materijal) cmbMatrijal.getSelectedItem());
        super.spremi();
        repaint();
    }

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (lstAnalizaMaterijala.getSelectedValue() == null) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        obrisi();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolicinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKolicinaActionPerformed

    private void txtJedinicnaCijenaMaterijalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJedinicnaCijenaMaterijalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJedinicnaCijenaMaterijalActionPerformed

    private void txtCijenaMaterijalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCijenaMaterijalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCijenaMaterijalActionPerformed

    private void lstAnalizaMaterijalaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAnalizaMaterijalaValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        try {
            this.entitet = lstAnalizaMaterijala.getSelectedValue();
            txtJedinicaMjere.setText(lstAnalizaMaterijala.getSelectedValue().getJedinicaMjere());
            txtKolicina.setText(lstAnalizaMaterijala.getSelectedValue().getKolicina().toString());
            txtJedinicnaCijenaMaterijal.setText(lstAnalizaMaterijala.getSelectedValue().getJedinicnaCijenaMaterijal().toString());
            txtCijenaMaterijal.setText(lstAnalizaMaterijala.getSelectedValue().getCijenaMaterijal().toString());
            cmbOznakaNorme.setSelectedItem(entitet.getAnalizaCijene());
            cmbMatrijal.setSelectedItem(entitet.getMaterijal());
            tarOpisNorme.setText(entitet.getAnalizaCijene().getOpis());
            
//            DefaultListModel<Materijal> m = new DefaultListModel<>();
//            lstAnalizaMaterijala.setModel(m);
//            entitet.getMaterijal().forEach((s) -> {
//                m.addElement(s);
//            });
//            ucitajMaterijal();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_lstAnalizaMaterijalaValueChanged

    private void cmbOznakaNormeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOznakaNormeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOznakaNormeActionPerformed

    private void cmbMatrijalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMatrijalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMatrijalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JComboBox<Materijal> cmbMatrijal;
    private javax.swing.JComboBox<AnalizaCijene> cmbOznakaNorme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrupaRadova1;
    private javax.swing.JLabel lblCijenaMaterijala;
    private javax.swing.JLabel lblJedinicaMjere;
    private javax.swing.JLabel lblJedinicnaCijena;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblMaterijal;
    private javax.swing.JLabel lblOznakaNorme;
    private javax.swing.JList<AnalizaMaterijal> lstAnalizaMaterijala;
    private javax.swing.JTextArea tarOpisNorme;
    private javax.swing.JTextField txtCijenaMaterijal;
    private javax.swing.JTextField txtJedinicaMjere;
    private javax.swing.JTextField txtJedinicnaCijenaMaterijal;
    private javax.swing.JTextField txtKolicina;
    // End of variables declaration//GEN-END:variables

    private void ucitajAnalizaCijene() {
        DefaultComboBoxModel<AnalizaCijene> m = new DefaultComboBoxModel<>();
        cmbOznakaNorme.setModel(m);
        List<AnalizaCijene> oznakaNorme = HibernateUtil.getSession().
                createQuery("from AnalizaCijene a where "
                        + "a.obrisan=false  ").list();

        for (AnalizaCijene p : oznakaNorme) {

            m.addElement(p);
            cmbOznakaNorme.setSelectedItem(p);

        }

    }

    private void ucitajMaterijal() {
        DefaultComboBoxModel<Materijal> m = new DefaultComboBoxModel<>();
        cmbMatrijal.setModel(m);
        List<Materijal> materijal = HibernateUtil.getSession().createQuery("from Materijal a where " + "a.obrisan=false  ").list();

        for (Materijal p : materijal) {

            m.addElement(p);
            cmbMatrijal.setSelectedItem(p);

        }

    }
    
//    private void ucitajMaterijal() {
//        List<Materijal> m = new ArrayList<>();
//        lstAnalizaMaterijala = HibernateUtil.getSession().createQuery("from Materijal a where a.obrisan=false").list();
//        lstAnalizaMaterijala.stream().forEach((p) -> {
//            if (entitet != null) {
//                boolean dodaj = true;
//                for (Materijal materijal : entitet.getMaterijal()) {
//                    if (p.getId().equals(materijal.getId())) {
//                        dodaj = false;
//                        break;
//                    }
//                }
//                if (dodaj) {
//                    m.add(p);
//                }
//            }
//
//        });
//
//    }

}
