/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kovacevic.view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Marko Kovačević
 */
public class Izbornik extends javax.swing.JFrame {
//nasljedjje se form??

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        setTitle("Završni rad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEraDijagram = new javax.swing.JButton();
        lblGithub = new javax.swing.JLabel();
        btnUnosRadMaterijal = new javax.swing.JButton();
        btnUnosAnalizaCijene = new javax.swing.JButton();
        btnTroskovnici = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));

        btnEraDijagram.setText("<html><center>ERA<br> Dijagram</center></html>");
        btnEraDijagram.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEraDijagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraDijagramActionPerformed(evt);
            }
        });

        lblGithub.setText("Github");
        lblGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGithubMouseClicked(evt);
            }
        });

        btnUnosRadMaterijal.setText("Rad i materijal");
        btnUnosRadMaterijal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnosRadMaterijal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosRadMaterijalActionPerformed(evt);
            }
        });

        btnUnosAnalizaCijene.setText("Analize cijene");
        btnUnosAnalizaCijene.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnosAnalizaCijene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosAnalizaCijeneActionPerformed(evt);
            }
        });

        btnTroskovnici.setText("Troškovnici");
        btnTroskovnici.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTroskovnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroskovniciActionPerformed(evt);
            }
        });

        jButton1.setText("Test Izbornik + JPanel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGithub))
                    .addComponent(btnEraDijagram)
                    .addComponent(btnUnosRadMaterijal, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(btnUnosAnalizaCijene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTroskovnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEraDijagram, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblGithub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUnosRadMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnosAnalizaCijene, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTroskovnici, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEraDijagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraDijagramActionPerformed
        new EraDijagram().setVisible(true);
    }//GEN-LAST:event_btnEraDijagramActionPerformed

    private void lblGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGithubMouseClicked

        try {
            Runtime.getRuntime().exec("cmd /c start https://github.com/mk0v4 ");
        } catch (IOException ex) {
            Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblGithubMouseClicked

    private void btnUnosRadMaterijalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosRadMaterijalActionPerformed
        new FormaRadMaterijal().setVisible(true);
    }//GEN-LAST:event_btnUnosRadMaterijalActionPerformed

    private void btnUnosAnalizaCijeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosAnalizaCijeneActionPerformed
        new FormaAnalizaCijene().setVisible(true);
    }//GEN-LAST:event_btnUnosAnalizaCijeneActionPerformed

    private void btnTroskovniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroskovniciActionPerformed
        new FormaTroskovnici().setVisible(true);
    }//GEN-LAST:event_btnTroskovniciActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TestIzbornik().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEraDijagram;
    private javax.swing.JButton btnTroskovnici;
    private javax.swing.JButton btnUnosAnalizaCijene;
    private javax.swing.JButton btnUnosRadMaterijal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblGithub;
    // End of variables declaration//GEN-END:variables
}
