/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kovacevic.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.LayoutManager;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import sun.swing.SwingAccessor;

/**
 *
 * @author Marko Kovačević
 */
public class TestIzbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public TestIzbornik() {
        initComponents();
        setTitle("Završni rad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEraDijagram = new javax.swing.JButton();
        lblGithub = new javax.swing.JLabel();
        btnUnosRadMaterijal = new javax.swing.JButton();
        btnUnosAnalizaCijene = new javax.swing.JButton();
        btnTroskovnici = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPodatci = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 350));

        btnEraDijagram.setText("<html><center>ERA<br> Dijagram</center></html>");
        btnEraDijagram.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEraDijagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraDijagramActionPerformed(evt);
            }
        });

        lblGithub.setText("Github");
        lblGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGithubMouseClicked(evt);
            }
        });

        btnUnosRadMaterijal.setText("Rad i materijal");
        btnUnosRadMaterijal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnosRadMaterijal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosRadMaterijalActionPerformed(evt);
            }
        });

        btnUnosAnalizaCijene.setText("Analize cijene");
        btnUnosAnalizaCijene.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnosAnalizaCijene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosAnalizaCijeneActionPerformed(evt);
            }
        });

        btnTroskovnici.setText("Troškovnici");
        btnTroskovnici.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTroskovnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroskovniciActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnlPodatci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPodatci.setMinimumSize(new java.awt.Dimension(850, 350));
        pnlPodatci.setLayout(new javax.swing.BoxLayout(pnlPodatci, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(pnlPodatci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEraDijagram, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnosRadMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnosAnalizaCijene, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTroskovnici, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGithub, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEraDijagram, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblGithub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUnosRadMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnosAnalizaCijene, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTroskovnici, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEraDijagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraDijagramActionPerformed
        pnlPodatci.removeAll();
        pnlPodatci.add(new TestEraDijagram());
        pnlPodatci.validate();
        jScrollPane1.validate();
    }//GEN-LAST:event_btnEraDijagramActionPerformed

    private void lblGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGithubMouseClicked

        try {
            Runtime.getRuntime().exec("cmd /c start https://github.com/mk0v4 ");
        } catch (IOException ex) {
            Logger.getLogger(TestIzbornik.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblGithubMouseClicked

    private void btnUnosRadMaterijalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosRadMaterijalActionPerformed
        pnlPodatci.removeAll();
        pnlPodatci.add(new TestFormaRadMaterijal());
        pnlPodatci.validate();
        jScrollPane1.validate();

    }//GEN-LAST:event_btnUnosRadMaterijalActionPerformed

    private void btnUnosAnalizaCijeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosAnalizaCijeneActionPerformed
        pnlPodatci.removeAll();
        pnlPodatci.add(new TestFormaAnalizaCijene());
        pnlPodatci.validate();
        jScrollPane1.validate();        
    }//GEN-LAST:event_btnUnosAnalizaCijeneActionPerformed

    private void btnTroskovniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroskovniciActionPerformed
        new FormaTroskovnici().setVisible(true);
    }//GEN-LAST:event_btnTroskovniciActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        new TestIzbornik().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEraDijagram;
    private javax.swing.JButton btnTroskovnici;
    private javax.swing.JButton btnUnosAnalizaCijene;
    private javax.swing.JButton btnUnosRadMaterijal;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGithub;
    private javax.swing.JPanel pnlPodatci;
    // End of variables declaration//GEN-END:variables
}
